1 Command: Procedure assemblestructmtx_main understood as oas_main.assemblestructmtx_main
2 Command: Procedure assembleaeromtx_main understood as oas_main.assembleaeromtx_main
3 Command: Procedure mult_main understood as oas_main.mult_main
4 Command: Procedure calc_vonmises_main understood as oas_main.calc_vonmises_main
5 Command: unit vonmises: not found
6 calc_vonmises_main: (DF02) Potential aliasing in calling function unit, between arguments 1 2
7 calc_vonmises_main: (DF02) Potential aliasing in calling function unit, between arguments 1 2
8 assemblestructmtx_main: (DD15) Module solveroutines is not defined
9 assemblestructmtx_main: (TC33) External procedure solve is not declared
10 assemblestructmtx_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(out) Arg3=(in)
11 matmul2c: (TC16) Type mismatch in assignment: COMPLEX*8[*,*] receives REAL
12 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8 receives DOUBLE PRECISION
13 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
14 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3,*,*] receives REAL
15 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
16 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
17 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
18 biotsavart: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
