1 Command: Procedure assemblesparsemtx_main understood as oas_main.assemblesparsemtx_main
2 Command: Procedure assemblestructmtx_main understood as oas_main.assemblestructmtx_main
3 Command: Procedure assembleaeromtx_main understood as oas_main.assembleaeromtx_main
4 assemblestructmtx_main: (DD15) Module solveroutines is not defined
5 assemblestructmtx_main: (TC33) External procedure solve is not declared
6 assemblestructmtx_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(out) Arg3=(in)
7 assembleaeromtx_main: (TC16) Type mismatch in assignment: REAL*8 receives DOUBLE PRECISION
