1 Command: Procedure assemblestructmtx_main understood as oas_main.assemblestructmtx_main
2 Command: Procedure assembleaeromtx_main understood as oas_main.assembleaeromtx_main
3 Command: Procedure mult_main understood as oas_main.mult_main
4 assemblestructmtx_main: (DD15) Module solveroutines is not defined
5 assemblestructmtx_main: (TC33) External procedure solve is not declared
6 assemblestructmtx_main: Command: Input variable(s) x have their derivative modified in assemblestructmtx_main: added to independents
7 assemblestructmtx_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(in;out) Arg3=(in)
8 matmul2c: (TC16) Type mismatch in assignment: COMPLEX*8[*,*] receives REAL
9 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8 receives DOUBLE PRECISION
10 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
11 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3,*,*] receives REAL
12 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
13 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
14 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
15 assembleaeromtx_main: Command: Input variable(s) mtx have their derivative modified in assembleaeromtx_main: added to independents
16 biotsavart: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
