1 Command: Procedure assemblestructmtx_main understood as oas_main.assemblestructmtx_main
2 Command: Procedure assembleaeromtx_main understood as oas_main.assembleaeromtx_main
3 Command: Procedure mult_main understood as oas_main.mult_main
4 Command: Procedure calc_vonmises_main understood as oas_main.calc_vonmises_main
5 Command: unit vonmises: not found
6 calc_vonmises_main: (DF02) Potential aliasing in calling function unitc, between arguments 1 2
7 calc_vonmises_main: (DF02) Potential aliasing in calling function unitc, between arguments 1 2
8 calc_vonmises_main: Command: Input variable(s) vonmises have their derivative modified in calc_vonmises_main: added to independents
9 assemblestructmtx_main: (DD15) Module solveroutines is not defined
10 assemblestructmtx_main: (TC33) External procedure solve is not declared
11 assemblestructmtx_main: Command: Input variable(s) x have their derivative modified in assemblestructmtx_main: added to independents
12 assemblestructmtx_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(in;out) Arg3=(in)
13 matmul2c: (TC16) Type mismatch in assignment: COMPLEX*8[*,*] receives REAL
14 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8 receives DOUBLE PRECISION
15 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
16 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3,*,*] receives REAL
17 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
18 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
19 assembleaeromtx_main: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
20 assembleaeromtx_main: Command: Input variable(s) mtx have their derivative modified in assembleaeromtx_main: added to independents
21 biotsavart: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
