function coupled_plotdata(mesh, loads)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 21-Jul-2016 19:39:18

n = size(mesh,1)/2;  % number of spanwise points

% Rearrange mesh array to order the wing points for drawing
tmpmesh = zeros(size(mesh,1)+1,size(mesh,2));
tmpmesh(1:n,:) = mesh(1:n,:);
tmpmesh(n+1:end-1,:) = flipud(mesh(n+1:end,:));
tmpmesh(end,:) = mesh(1,:);
% mesh = tmp;
M1 = tmpmesh(:,1);  M2 = tmpmesh(:,2);  M3 = tmpmesh(:,3);
L1 = loads(:,1); L3 = loads(:,2); L3 = loads(:,3); 
L4 = loads(:,4); L5 = loads(:,5); L6 = loads(:,6);


fem_origin = 0.35;   % fem origin at 0.35*chord



% mesh(end,:) = [];  % remove first point at end
for i = 1:n  % x cooridates for force,moments
    Lx(i) = fem_origin*(mesh(i+n,1) - mesh(i,1)) + mesh(i,1); 
end
Lx = Lx';
% interpolate to get y and z coordinates
for i = 1:n
    x = [mesh(i,1),mesh(i+n,1)];
    y = [mesh(i,2),mesh(i+n,2)];
    z = [mesh(i,3),mesh(i+n,3)];
    Ly(i) = interp1(x,y,Lx(i));
    Lz(i) = interp1(x,z,Lx(i));
end
Ly = Ly'; Lz = Lz';

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create mesh plot
plot3(M1,M2,M3,'-bo','LineWidth',1.5,'MarkerFaceColor','b');
% Create labels
xlabel(axes1,'X-axis (chord)');
ylabel(axes1,'Y-axis (span)');
zlabel(axes1,'Z-axis');
zlimits = .015;
% zlim(axes1,[-zlimits*.5,zlimits]);
fill3(M1,M2,M3,[204 229 255]./255);  % fill in wing
plot3(Lx,Ly,Lz,'-ro','LineWidth',1.5,'MarkerFaceColor','r','MarkerSize',10); % vector origins
% scalemag = 1e-5;    % scale vectors to make them relative to wing size
scalemag = 1;
autoscalefactor = .05;
autoscalefactor = .8;
% autoscale = 'off';
tmploads = loads*scalemag;
Fu = tmploads(:,1); Fv = tmploads(:,2); Fw = tmploads(:,3);
Mu = tmploads(:,4); Mv = tmploads(:,5); Mw = tmploads(:,6);
Lmag = (Fu.^2 + Fv.^2 + Fw.^2).^.5
quiver3(Lx,Ly,Lz,Fu,Fv,Fw,autoscalefactor*.05,'Linewidth',2,'Color','r');
quiver3(Lx,Ly,Lz,Mu,Mv,Mw,autoscalefactor,'Linewidth',2,'Color','m');
% scatter3(M1,M2,M3,'MarkerFaceColor','blue','SizeData',3);


% Create force and moment vectors at fem_origin for each 


% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-20 20]);
view(axes1,[78.1 10.8]);
box(axes1,'on');
grid(axes1,'on');
