1 Command: Took subroutine mult as default differentiation root
2 assemblesparsemtx: (TC16) Type mismatch in assignment: COMPLEX*8[12,12] receives REAL
3 assemblesparsemtx: (TC16) Type mismatch in assignment: COMPLEX*8[*] receives REAL
4 assemblesparsemtx: (TC16) Type mismatch in assignment: COMPLEX*8[12,12] receives REAL
5 assemblestructmtx: (TC16) Type mismatch in assignment: COMPLEX*8[*,*] receives REAL
6 assemblestructmtx: (TC16) Type mismatch in assignment: COMPLEX*8[12,12] receives REAL
7 assemblestructmtx: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
8 assemblestructmtx: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
9 matmul2: (TC16) Type mismatch in assignment: COMPLEX*8[*,*] receives REAL
10 assembleaeromtx: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
11 assembleaeromtx: (TC16) Type mismatch in assignment: COMPLEX*8[3,*,*] receives REAL
12 assembleaeromtx: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
13 assembleaeromtx: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
14 assembleaeromtx: (TC16) Type mismatch in assignment: COMPLEX*8[3] receives REAL
15 biotsavart: (TC16) Type mismatch in assignment: COMPLEX*8 receives REAL
